// Flat config (ESLint 9). Recommended presets only — same reasoning as
// limitkit: a small library does not need a bespoke rule set to maintain.
// The floor is "lint runs and can fail", not "lint encodes taste".
import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    // dist/ is generated by `tsc`.
    ignores: ['dist/**', 'node_modules/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: { globals: globals.node },
  },
  {
    // Tests are plain Node ESM running under `node --test`.
    files: ['test/**/*.js'],
    languageOptions: { globals: { ...globals.node, ...globals.nodeBuiltin } },
  },
)
