// Flat config (ESLint 9). Recommended presets only — same reasoning as
// limitkit: a small library does not need a bespoke rule set to maintain.
// The floor is "lint runs and can fail", not "lint encodes taste".
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // dist/ is generated by `tsc`.
    //
    // .claude/worktrees/ holds per-session git worktrees — each a full second
    // checkout of this repo with its own tsconfig.json. ESLint walked into
    // them: `eslint .` in a checkout with one sibling worktree failed with 44
    // parse errors ("multiple candidate TSConfigRootDirs are present"),
    // reporting files that were on somebody else's branch. Whatever is wrong
    // in another worktree is that branch's lint run to fail, not this one's.
    ignores: ['dist/**', 'node_modules/**', '.claude/worktrees/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: { globals: globals.node },
  },
  {
    // Tests are plain Node ESM running under `node --test`.
    files: ['test/**/*.js'],
    languageOptions: { globals: { ...globals.node, ...globals.nodeBuiltin } },
  },
);
